stages:
    - build
    - release

maven-build:
    image: maven:3.3.9-jdk-8
    stage: build
    script:
        - mvn -B package
    artifacts:
        paths:
            - target/*.jar
    only: master

release:
    stage: release
    only: tags
    release:
        name: $CI_COMMIT_TAG
        description: $CI_COMMIT_MESSAGE
        assets:
            - name: DiscovShows.jar
              path: target/*.jar
