stages:
    - build
    - release

maven-build:
    image: maven:3.3.9-jdk-8
    stage: build
    script:
        - mvn -B package
    only: 
        - master

release:
    stage: release
    only:
        - tags
    script: make changelog | tee changelog.txt
    artifacts:
        paths:
            - target/*.jar
    release:
        name: $CI_COMMIT_TAG
        tag_name: $CI_COMMIT_TAG
        description: changelog.txt

