main: nl.parrotlync.discovshows.DiscovShows
name: DiscovShows
version: 1.3.3
description: Show plugin for the Discovery Network
api-version: 1.12
depend: [WorldEdit]
author: ParrotLync
commands:
  show:
    description: Main DiscovShows command
    usage: /show
permissions:
  discovshows.operate:
    default: op
    description: Permission to operate shows
  discovshows.effects:
    default: op
    description: Permission to use effects